### ISSUE TITLE
GANSynth KeyError: 'tfds_data_dir'

### ISSUE THREAD

**Issue by Junpyer** [magenta/magenta#1794]
Hi, by two days the GANSynth's Colab Demo give me an error on Environment Setup:

```
Load model from /content/gansynth/acoustic_only/stage_00012/./model.ckpt-11000000
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-bad1649e76e0> in <module>()
     65 tf.reset_default_graph()
     66 flags = lib_flags.Flags({'batch_size_schedule': [BATCH_SIZE]})
---> 67 model = lib_model.Model.load_from_path(CKPT_DIR, flags)
     68 
     69 # Helper functions

4 frames
/usr/local/lib/python3.6/dist-packages/magenta/models/gansynth/lib/model.py in load_from_path(cls, path, flags)
    175     batch_size = flags.get('eval_batch_size',
    176                            train_util.get_batch_size(stage_id, **flags))
--> 177     model = cls(stage_id, batch_size, flags)
    178     model.saver.restore(model.sess, ckpt)
    179     return model

/usr/local/lib/python3.6/dist-packages/magenta/models/gansynth/lib/model.py in __init__(self, stage_id, batch_size, config)
    191     """
    192     data_helper = data_helpers.registry[config['data_type']](config)
--> 193     real_images, real_one_hot_labels = data_helper.provide_data(batch_size)
    194 
    195     # gen_one_hot_labels = real_one_hot_labels

/usr/local/lib/python3.6/dist-packages/magenta/models/gansynth/lib/data_helpers.py in provide_data(self, batch_size)
     64     with tf.name_scope('inputs'):
     65       with tf.device('/cpu:0'):
---> 66         dataset = self.dataset.provide_dataset()
     67         dataset = dataset.shuffle(buffer_size=1000)
     68         dataset = dataset.map(self._map_fn, num_parallel_calls=4)

/usr/local/lib/python3.6/dist-packages/magenta/models/gansynth/lib/datasets.py in provide_dataset(self)
    116       return wave, one_hot_label, label, example['instrument']['source']
    117 
--> 118     dataset = self._get_dataset_from_tfds()
    119     dataset = dataset.map(
    120         _parse_nsynth, num_parallel_calls=tf.data.experimental.AUTOTUNE)

/usr/local/lib/python3.6/dist-packages/magenta/models/gansynth/lib/datasets.py in _get_dataset_from_tfds(self)
     65       dataset = tfds.load(
     66           'nsynth/gansynth_subset:2.3.*',
---> 67           data_dir=self._config['tfds_data_dir'],
     68           split=tfds.Split.TRAIN,
     69           download=False)

KeyError: 'tfds_data_dir'
```

How can I resolve?

**Comment by Klunio** [comment]
same problem here~

**Comment by YongBaekCho** [comment]
same problem

**Comment by YB-Joe** [comment]
I have same problem.. Any solutions?

**Comment by adarob** [comment]
That value needs to be set to 'gs://tfds-data/datasets'. I can fix this on Monday if nobody gets to it first!

**Comment by YB-Joe** [comment]
@adarob Thank you sir. I have set to 'gs://tfds-data/datasets' , but still don't get it.

**Comment by adarob** [comment]
Fix is on the way -- should be out in a day or two. Sorry for the issue!

**Comment by YB-Joe** [comment]
@adarob Thank you!

**Comment by YB-Joe** [comment]
@adarob Hello! Is it fixed?

**Comment by adarob** [comment]
Thanks for the reminder. Unfortunately it hasn't been updated on the colab server yet. If it's not up tomorrow, I will see if I can figure out what's going on.

**Comment by YB-Joe** [comment]
@adarob Thanks for responding so quickly!

**Comment by Junpyer** [comment]
@adarob Thank you so much!

**Comment by Junpyer** [comment]
Hi, the Colab give me a new error :(

```
NotFoundError                             Traceback (most recent call last)
<ipython-input-3-98d96ca35b58> in <module>()
     66     'tfds_data_dir': "gs://tfds-data/datasets",
     67 })
---> 68 model = lib_model.Model.load_from_path(CKPT_DIR, flags)
     69 
     70 # Helper functions

2 frames
/usr/local/lib/python3.6/dist-packages/magenta/models/gansynth/lib/model.py in load_from_path(cls, path, flags)
    161     flags.print_values()
    162     # Get list_of_directories
--> 163     train_sub_dirs = sorted([sub_dir for sub_dir in tf.gfile.ListDirectory(path)
    164                              if sub_dir.startswith('stage_')])
    165     if not train_sub_dirs:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py in list_directory(dirname)
    669     errors.NotFoundError if directory doesn't exist
    670   """
--> 671   return list_directory_v2(dirname)
    672 
    673 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py in list_directory_v2(path)
    692         node_def=None,
    693         op=None,
--> 694         message="Could not find directory {}".format(path))
    695 
    696   # Convert each element to string, since the return values of the

NotFoundError: Could not find directory /content/gs:/magentadata/models/gansynth/acoustic_only
```

**Comment by adarob** [comment]
Try now. This should be fixed!

**Comment by jamesliu** [comment]
I still have the same issue even after updating magenta to 2.1.3 with pip install -U magenta. Is the fix already in the latest version? Thanks.
![Screen Shot 2020-11-23 at 10 55 19 AM](https://user-images.githubusercontent.com/41763/100003408-e3709b80-2d7a-11eb-98d6-09575e8179c7.png)
